apps/surveys/urls.py
from django.conf.urls import patterns, include, url



urlpatterns = patterns('surveys.views',
	url(r'^home/$', 'home'),															# /surveys/home/
	url(r'^create/$', 'create'),														# /surveys/create/
	url(r'^(?P<survey_id>\d+)/newquestion/$', 'newQuestion'),							# /surveys/<survey_id>/newquestion/
	url(r'^(?P<survey_id>\d+)/editquestion/(?P<question_no>\d+)/$', 'editQuestion'), 	# /surveys/<survey_id>/editquestion/<question_id>/
	url(r'^(?P<survey_id>\d+)/view/$', 'view'),											# /surveys/<survey_id>/view/
	url(r'^(?P<survey_id>\d+)/edit/$', 'edit'),											# /surveys/<survey_id>/edit/
	url(r'^(?P<survey_id>\d+)/delete/$', 'deleteSurvey'),								# /surveys/<survey_id>/delete/
	url(r'^(?P<survey_id>\d+)/deletequestion/(?P<question_no>\d+)/$', 'deleteQuestion'),# /surveys/<survey_id>/deletequestion/<question_id>/
	url(r'^(?P<survey_id>\d+)/$', 'attempt'),											# /surveys/<survey_id>/
	url(r'^completed/$', 'completed'),                                                  # /surveys/completed/
	url(r'^(?P<survey_id>\d+)/reset/$', 'reset'),   									# /surveys.<survey_id>/reset/                       
	url(r'^(?P<survey_id>\d+)/responses/$', 'responses'),								# /surveys.<survey_id>/responses/
	)


duckingawesome/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'duckingawesome.views.home', name='home'),
    # url(r'^duckingawesome/', include('duckingawesome.foo.urls')),
	
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^surveys/', include('surveys.urls')),
    url(r'', include('accounts.urls')),
)

apps/surveys/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Survey(models.Model):
	user = models.ForeignKey(User)
	description = models.CharField(max_length=200)
	pub_date = models.DateTimeField(auto_now_add=True)
	mod_date = models.DateTimeField(auto_now=True)
	
	def __unicode__(self):
		return self.description
	

class Question(models.Model):
	QUESTION_CHOICES = (
		('RB','Radio Button'),
		('CB','Check Box'),
		('TF','Text Field'),
		('NI','Numeric Input'),
	)
	
	survey = models.ForeignKey(Survey)
	description = models.CharField(max_length=200)
	questionno = models.IntegerField()
	questiontype = models.CharField(max_length=2, choices=QUESTION_CHOICES)
	
	class Meta:
		ordering = ['questionno']
	
	def __unicode__(self):
		return self.description


class Choice(models.Model):
	question = models.ForeignKey(Question)
	description = models.CharField(max_length=50, null=True)
	votes = models.IntegerField(null=True)
	choiceno = models.IntegerField(null=True)
	
	class Meta:
		ordering = ['choiceno']
	
	def __unicode__(self):
		return self.description
		
class Response(models.Model):
	survey = models.ForeignKey(Survey)
	responsetime = models.IntegerField(default=0)
	ipaddress = models.CharField(max_length=50, null=True)
	valid = models.BooleanField(default=False)
	accessdate = models.DateTimeField(auto_now_add=True)
	
	def __unicode__(self):
		return self.description

apps/surveys/forms.py
from django import forms

# Create your forms here.

class SurveyForm(forms.Form):
	description = forms.CharField(max_length=200)
	

class QuestionForm(forms.Form):
	description = forms.CharField(max_length=200)
	
	choice1 = forms.CharField(max_length=200, required=False)
	choice2 = forms.CharField(max_length=200, required=False)
	choice3 = forms.CharField(max_length=200, required=False)
	choice4 = forms.CharField(max_length=200, required=False)

apps/surveys/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime, time, date, timedelta
from accounts.models import UserProfile
from .models import Survey, Question, Choice, Response
from .forms import *


@login_required
def home(request):
	surveyList = Survey.objects.filter(user=request.user)
	for survey in surveyList:
		for response in survey.response_set.all():
			if response.valid == False:
				response.delete()
	urllink = request.build_absolute_uri()
	urllink = str.replace(urllink, 'home/', '')
	return render(request, 'surveys/home.html', {'surveyList': surveyList, 'urllink': urllink})

	
@login_required
def view(request, survey_id):
	user = request.user
	try:
		survey = user.survey_set.get(pk=survey_id)
	except Survey.DoesNotExist:
		raise Http404
		
	return render(request, 'surveys/view.html', {'survey_id': survey_id, 'survey': survey})
        
        
@login_required
def create(request):
	user = request.user
	form = SurveyForm(request.POST or None)
	
	if form.is_valid():
		survey = user.survey_set.create(description=form.cleaned_data['description'])		
		
		return redirect('surveys.views.newQuestion', survey_id=survey.id )
		
	return render(request, 'surveys/create.html', {'form': form})

	
@login_required
@csrf_exempt
def newQuestion(request, survey_id):
	user = request.user
	form = QuestionForm(request.POST or None)
	try:
		survey = user.survey_set.get(pk=survey_id)
	except Survey.DoesNotExist:
		raise Http404
	
	if form.is_valid():
		qntype = request.POST['qntype']
		qnno = 1
		while survey.question_set.filter(questionno = qnno):
			qnno += 1
		if qntype == 'CB' or qntype == 'RB':
			if form.cleaned_data['choice1'] or form.cleaned_data['choice2'] or form.cleaned_data['choice3'] or form.cleaned_data['choice4']:
				question = survey.question_set.create(description=form.cleaned_data['description'], questionno = qnno)
				question.questiontype = qntype
				question.save()
				if form.cleaned_data['choice1']:
					question.choice_set.create(description=form.cleaned_data['choice1'], votes=0, choiceno=1)
				if form.cleaned_data['choice2']:
					question.choice_set.create(description=form.cleaned_data['choice2'], votes=0, choiceno=2)
				if form.cleaned_data['choice3']:
					question.choice_set.create(description=form.cleaned_data['choice3'], votes=0, choiceno=3)
				if form.cleaned_data['choice4']:
					question.choice_set.create(description=form.cleaned_data['choice4'], votes=0, choiceno=4)
					
				try:
					request.POST['end']
					return redirect('/surveys/home/')
				except:
					pass
			else:
				messages.error(request, u'Please enter at least 1 choice.')
		else:
			question = survey.question_set.create(description=form.cleaned_data['description'], questionno = qnno)
			question.questiontype = qntype
			question.save()
			survey.save()
			
			try:
				request.POST['end']
				return redirect('/surveys/home/')
			except:
				pass

	return render(request, 'surveys/newquestion.html', {'form': form, 'survey_id': survey_id, 'survey': survey,})
	
	
@login_required
@csrf_exempt
def editQuestion(request, survey_id, question_no):
	user = request.user
	
	try:
		survey = user.survey_set.get(pk=survey_id)
	except Survey.DoesNotExist:
		raise Http404

	try:
		question = survey.question_set.get(questionno=question_no)
	except Survey.DoesNotExist:
		raise Http404
		
	initial = { 'description': question.description, 'questionno': question.questionno }
	
	choicelist = ['choice1', 'choice2', 'choice3', 'choice4']
	
	choiceno = 1
	
	for ch in choicelist:
		if question.choice_set.filter(choiceno=choiceno):
			choice = question.choice_set.get(choiceno=choiceno)
			description = choice.description
			initial[ch] = description
		else:
			initial[ch] = ''
		choiceno = choiceno + 1
		
	form = QuestionForm(request.POST or None, initial = initial)
	if form.is_valid():
		qntype = request.POST['qntype']
		if qntype == 'CB' or qntype == 'RB':
			if form.cleaned_data['choice1'] or form.cleaned_data['choice2'] or form.cleaned_data['choice3'] or form.cleaned_data['choice4']:
				question.description = form.cleaned_data['description']
				if question.questiontype == 'TF' or question.questiontype == 'NI':
					for choice in question.choice_set.all():
						choice.delete()
				question.questiontype = qntype
				question.save()
				if question.choice_set.filter(choiceno=1):
					choice = question.choice_set.get(choiceno=1)
					if form.cleaned_data['choice1']:
						choice.description = form.cleaned_data['choice1']
						choice.save()
					else:
						choice.delete()
				else:
					if form.cleaned_data['choice1']:
						question.choice_set.create(description=form.cleaned_data['choice1'], votes=0, choiceno=1)
				if question.choice_set.filter(choiceno=2):
					choice = question.choice_set.get(choiceno=2)
					if form.cleaned_data['choice2']:
						choice.description = form.cleaned_data['choice2']
						choice.save()
					else:
						choice.delete()
				else:
					if form.cleaned_data['choice2']:
						question.choice_set.create(description=form.cleaned_data['choice2'], votes=0, choiceno=2)
				if question.choice_set.filter(choiceno=2):
					choice = question.choice_set.get(choiceno=2)
					if form.cleaned_data['choice2']:
						choice.description = form.cleaned_data['choice2']
						choice.save()
					else:
						choice.delete()
				else:
					if form.cleaned_data['choice2']:
						question.choice_set.create(description=form.cleaned_data['choice2'], votes=0, choiceno=2)
				if question.choice_set.filter(choiceno=3):
					choice = question.choice_set.get(choiceno=3)
					if form.cleaned_data['choice3']:
						choice.description = form.cleaned_data['choice3']
						choice.save()
					else:
						choice.delete()
				else:
					if form.cleaned_data['choice3']:
						question.choice_set.create(description=form.cleaned_data['choice3'], votes=0, choiceno=3)
				if question.choice_set.filter(choiceno=4):
					choice = question.choice_set.get(choiceno=4)
					if form.cleaned_data['choice4']:
						choice.description = form.cleaned_data['choice4']
						choice.save()
					else:
						choice.delete()
				else:
					if form.cleaned_data['choice4']:
						question.choice_set.create(description=form.cleaned_data['choice4'], votes=0, choiceno=4)
				messages.success(request, u'Your question has been edited.')
				survey.save()
			else:
				messages.error(request, u'Please enter at least 1 choice.')
		else:
			if question.questiontype != qntype:
				for choice in question.choice_set.all():
					choice.delete()
			question.description = form.cleaned_data['description']
			question.questiontype = qntype
			question.save()
			survey.save()
			
				
			messages.success(request, u'Your question has been edited.')
				
		return redirect('surveys.views.editQuestion', survey_id=survey_id , question_no=question_no,)
	
	return render(request, 'surveys/question.html', {'form': form, 
		'survey_id': survey_id, 
		'initial': initial, 
		'question_no': question_no,
		'qntype': question.questiontype,
		'survey': survey,})


@login_required
@csrf_exempt
def deleteSurvey(request, survey_id):
	user = request.user
	
	try:
		survey = user.survey_set.get(pk=survey_id)
	except Survey.DoesNotExist:
		raise Http404
		
	survey.delete()
	messages.success(request, u'Your survey has been deleted.')
	
	return redirect('/surveys/home/')


@login_required
@csrf_exempt
def deleteQuestion(request, survey_id, question_no):
	user = request.user
	
	try:
		survey = user.survey_set.get(pk=survey_id)
	except Survey.DoesNotExist:
		raise Http404
	
	try:
		question = survey.question_set.get(questionno=question_no)
	except Survey.DoesNotExist:
		raise Http404
	
	qnno = int(question_no)
	qnno = qnno + 1
	
	while survey.question_set.filter(questionno = qnno):
		nextqn = survey.question_set.get(questionno = qnno)
		nextqn.questionno = nextqn.questionno - 1
		nextqn.save()
		qnno = qnno + 1
		
	question.delete()
	survey.save()
	messages.success(request, u'Your question has been deleted.')
	
	if survey.question_set.filter(questionno = question_no):
		return redirect('surveys.views.editQuestion', survey_id=survey_id, question_no=question_no)
	else:
		return redirect('surveys.views.newQuestion', survey_id=survey_id)

		
@login_required
def edit(request, survey_id):
	user = request.user
	try:
		survey = user.survey_set.get(pk=survey_id)
		initial = {'description': survey.description}
	except Survey.DoesNotExist:
		raise Http404

	form = SurveyForm(request.POST or None, initial = initial)
	
	if form.is_valid():
		survey.description = form.cleaned_data['description']
		survey.save()
		
		messages.success(request, u'Your survey title has been edited.')
		
	return render(request, 'surveys/edit.html', {'form': form, 'survey_id': survey_id, 'survey': survey})


@csrf_exempt
def attempt(request, survey_id):
	
	survey = get_object_or_404(Survey, pk=survey_id)

	if request.method == 'GET':
		start = datetime.now() - datetime.combine(date.today() - timedelta(days=1), time(0, 0))
		starttime = start.days*86400+ start.seconds
		response = survey.response_set.create(responsetime=starttime, ipaddress=request.META.get('REMOTE_ADDR'))
	
	if request.method == 'POST':
		qnno = 1
		while survey.question_set.filter(questionno=qnno):
			question = survey.question_set.get(questionno=qnno)
			qnname = 'q' + str(qnno)
			if question.questiontype == 'TF':
				try: 
					request.POST[qnname]
					if request.POST[qnname]:

templates/surveys/completed.html
<!DOCTYPE html>
<html>
	<head>
		<title>DuckingAwesome</title>
		<script src="{{ STATIC_URL }}js/jquery-1.8.2.min.js"></script>
	<style type="text/css">
<!--
*{
	
	padding:0px;
	text-decoration:none;
}
#wrapper {
	margin-right:auto;
	margin-left:auto;
	width:960px;	
	display: block;
}
#header {
	height: 80px;
	border-bottom-width: 5px;
	border-bottom-style: solid;
	border-bottom-color: #000;
}
#DAlogo {
	float: left;
	margin-left:25px;
	margin-top:10px;
}
#footer {
	height: 40px;
	width:960px;
	border-top-width: 5px;
	border-top-style: solid;
	border-top-color: #000;
	float:left;
}
#footer p{
	font-family: Verdana, Geneva, sans-serif;
	font-size: 12px;
	margin:15px;
	text-align:center;
}
#copyright {
	font-style: italic;
	color: #666;
}
p{
	text-align:center;
	font-size:18px;
}
#contentColumn a, #contentColumn a:visited{
	color: #006;
	text-decoration:underline;
}
#contentColumn a:hover{
	color:#F90;
}
-->	
	 </style>
	</head>
<body>
<div id="wrapper">
	<div id="header">
		<div id="DAlogo">
			<img src="{{ STATIC_URL }}image/DAlogo.jpg" width="220" height="50" alt="duckingAwesomeLogo" onClick="parent.location='/'" />
		</div DAlogo>
  	</div header>
    <div id="contentColumn">
<p>Thank you for your time!</p>
<p>If you want to join Ducking Awesome,</p>
<p><a href="/">Click Here</a></p>

<script type="text/javascript">
	$(document).ready(function(){
		console.log('Ready');
	});
</script>
</div contentColumn>
		<div id="footer">
        	<p id="copyright">© 2012 DuckingAwesome </p>
		</div footer>
	</div wrapper>
</body>
</html>

templates/surveys/create.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
<!--
#createSurveyS1{
	padding: 10px;
	margin-top: 30px;
	margin-left: 30px;
	margin-bottom:30px;
}
h1 {
	margin-bottom: 20px;
	margin-left:20px;
	margin-top: 20px;
	font-weight:bold;
	font-size:28px;
}
label {
	padding-top:5px;
	font-weight:bold;
	padding-right:20px;
}
input{
	padding-top:2px;
	padding-bottom:2px;
	padding-right:5px;
	padding-left:5px;
}

.fieldWrapper{
	padding-top:10px;
	padding-bottom:10px;
}
#createSurveyTitle{
	padding-bottom:20px;
}
#id_description{
	width:30em;
}
-->
</style>
<h1>Create Survey Title</h1>
<form action="/surveys/create/" method="post" id="createSurveyS1">
	{% csrf_token %}
	<!--{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}-->
<div id="createSurveyTitle">

{{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ field.id_description.label_tag }}<label>Survey Title</label>: {{ form.description }}
        <span class="error">
        	{% for e in form.description.errors %}
            *{{e}}
            {% endfor %}
        </span>
    </div>
    </div createSurveyTitle>
	<input type="submit" value="Next" />
    <input id="DoneButton" type="button" value="Cancel" onClick="parent.location='/surveys/home'"/>
</form>


<script type="text/javascript">
	$(document).ready(function(){
		console.log('Ready');
	});
</script>

{% endblock %}

templates/surveys/edit.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
<!--
h1 {
	margin-left:20px;
	margin-top: 20px;
	font-weight:bold;
	font-size:28px;
}
label {
	padding-top:5px;
	font-weight:bold;
	padding-right:20px;
}
input{
	padding-top:2px;
	padding-bottom:2px;
	padding-right:5px;
	padding-left:5px;
	margin-right:5px;
}

.fieldWrapper{
	padding-top:10px;
	padding-bottom:10px;
	margin-left:5px;
}
#id_description{
	width:30em;
}
#responseB{
	padding-left:45px;
	font-weight:bold;
}
#textboxfield{
	width:50em;
	margin-top:10px;
	padding:2px;
	
}
#columnleft{
	float:left;
	width:120px;
	height:400px;
	border:#000 solid 2px;
	margin-right:10px;
	margin-bottom:20px;
	padding:20px;
}
#columnright{
	border:#000 solid 2px;
	width:740px;
	float:right;
	height:400px;
	margin-bottom:20px;
	padding:20px;
}
strong {
	text-decoration: underline;
	font-weight:bold;
}

li{
	margin-left:10px;
	color:red;
}
#columnright a, #columnright a:visited{
	color:#006;
	text-decoration:none;
}
li a:hover{
	color:#F60;
}
#surveyTitle{
	font-weight:bold;
	color:#000;
}
#columnleft span{
	text-decoration:underline;
	font-weight:bold;
}
#questionlist{
	margin-top:15px;
	margin-bottom:15px;
}
-->
</style>

<h1>Edit Survey</h1>

<div id="columnleft">

<a id="surveyTitle" href="/surveys/{{ survey_id }}/edit">Edit Survey Title</a>
<div id="questionlist">
<span>Question List</span>
</div questionlist>
{% for question in survey.question_set.all %}
<li><a href="/surveys/{{ survey_id }}/editquestion/{{ question.questionno }}/">Question {{ forloop.counter }}</a></li>
{% endfor %}

</div columnleft>
<div id="columnright">

<a href="/surveys/{{ survey_id }}/newquestion/">Create Question</a>

{% if messages %}
	<ul class="messages">
	{% for message in messages %}
	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	{% endfor %}</ul>
{% endif %}

<form action="/surveys/{{ survey_id }}/edit/" method="post">
	{% csrf_token %}
	<div class="fieldWrapper">
			<!--{{ form.description.errors }}-->
			<label for="id_description">Survey Title:</label>
			{{ form.description }}
            <span class="error">
        	{% for e in form.description.errors %}
            *{{e}}
            {% endfor %}
        	</span>
		</div>
	<input type="submit" value="Save" onclick="parent.location='/surveys/home'">
    <input type="button" value="Back" onclick="parent.location='/surveys/home'">
</form>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		console.log('Ready');
	});
</script>

{% endblock %}

templates/surveys/newquestion.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
<!--
h1 {
	margin-left:20px;
	margin-top: 20px;
	font-weight:bold;
	font-size:28px;
}

label {
	padding-top:5px;
	font-weight:bold;
	padding-right:20px;
}
button, #nextButton,#DoneButton, #endButton{
	padding-top:2px;
	padding-bottom:2px;
	padding-right:5px;
	padding-left:5px;
	margin-right:5px;
}
button{
	margin-bottom:20px;
}
.fieldWrapper{
	padding-top:10px;
	padding-bottom:10px;
	margin-left:20px;
}
#addSurveyQ{
	padding-bottom:10px;
}
#id_description{
	width:30em;
}
#id_choice1, #id_choice2, #id_choice3, #id_choice4{
	margin-left:10px;
	width:20em;
}
#responseB{
	font-weight:bold;
}
#columnleft span{
	text-decoration:underline;
	font-weight:bold;
	padding-bottom:10px;
}
#textboxfield{
	width:50em;
	margin-top:10px;
	padding:2px;
	margin-left:20px;
	
}
#textboxfield2{
	width:5em;
	margin-top:10px;
	padding:2px;
	margin-left:20px;
	
}
#columnleft{
	float:left;
	width:120px;
	height:400px;
	border:#000 solid 2px;
	margin-right:10px;
	margin-bottom:20px;
	padding:20px;
}
#columnright{
	border:#000 solid 2px;
	width:740px;
	float:right;
	height:400px;
	margin-bottom:20px;
	padding:20px;
}
li a, li a:visited{
	color:#006;
	text-decoration:none;
}
li a:hover{
	color:#F60;
}
#questionlist{
	margin-top:10px;
	margin-bottom:10px;
}
#addSurveyQ li{
	color: red;
	margin-left:25px;
}
strong{
	margin-left:20px;
}
-->
</style>
<h1>Create Survey Questions</h1>

<div id="columnleft">
<div id="questionlist"><span>Question List</span></div questionlist>
{% for question in survey.question_set.all %}
<li><a href="/surveys/{{ survey_id }}/editquestion/{{ question.questionno }}/">Question {{ forloop.counter }}</a></li>
{% endfor %}

</div columnleft>

<div id="columnright">
<div id="responseB"> Choose Response Type: <button id="radio">Radio</button><button id="text">Text</button><button id="check">Check</button><button id="number">Number</button><br></div>

<form method="POST" action="/surveys/{{ survey_id }}/newquestion/" id="addsurveyQF">
	<div id="addSurveyQ">
	{% if messages %}
	  
		{% for message in messages %}
		<div class="fieldWrapper">
			<label for="id_description">Question Title:</label>
			{{ form.description }}
            <span class="error">
            
        	{% for e in form.description.errors %}
            *{{e}}
            {% endfor %}
        	</span>
		</div>
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
	{% else %}
	{{ form.non_field_errors }}	
	<div class="fieldWrapper">
		<!--{{ form.description.errors }}-->
		<label for="id_description">Question Title:</label>
		<input id='id_description' type='text' name='description' maxlength='200' />
        <span class="error">
        	{% for e in form.description.errors %}
            *{{e}}
            {% endfor %}
        </span>
	</div>
	{% endif %}
    <div id="choices">
		<input type="hidden" name='qntype' value='RB'/>
        <strong>Response Type: </strong>Radio Button 
        
		<div class='fieldWrapper'> 
        	<input type="radio" disabled="disabled">
			<input id='id_choice1' type='text' name='choice1' maxlength='200' />
		</div>
		<div class='fieldWrapper'>
        	<input type="radio" disabled="disabled">
            <input id='id_choice2' type='text' name='choice2' maxlength='200' />
		</div>
		<div class='fieldWrapper'>
        	<input type="radio" disabled="disabled">
            <input id='id_choice3' type='text' name='choice3' maxlength='200' />
		</div>
		<div class='fieldWrapper'>
        	<input type="radio" disabled="disabled">
            <input id='id_choice4' type='text' name='choice4' maxlength='200' />
		</div>
	</div>
    </div addSurveyQ>
    <p><input id="nextButton" type="submit" value="Save and Next" /><input id="endButton" type="submit" name="end" value="Save and Exit" /><input id="DoneButton" type="button" value="Exit" onClick="parent.location='/surveys/home'"/></p>	
</form>
</div columnright>
<script type="text/javascript">
	$(document).ready(function(){
		$('#text').click(function(){
			$("#choices").replaceWith("<div id='choices'><input type='hidden' name='qntype' value='TF'/><strong>Response Type: </strong>Textbox <br><input type='text' name='example' id='textboxfield' value='example' readonly='readonly'/></div>");})
		$('#radio').click(function(){
			$("#choices").replaceWith("<div id='choices'><input type='hidden' name='qntype' value='RB'/><strong>Response Type: </strong>Radio Button <div class='fieldWrapper'><input type='radio' disabled='disabled'> <input id='id_choice1' type='text' name='choice1' maxlength='200' /></div><div class='fieldWrapper'><input type='radio' disabled='disabled'> <input id='id_choice2' type='text' name='choice2' maxlength='200' /></div><div class='fieldWrapper'><input type='radio' disabled='disabled'> <input id='id_choice3' type='text' name='choice3' maxlength='200' /></div><div class='fieldWrapper'><input type='radio' disabled='disabled'> <input id='id_choice4' type='text' name='choice4' maxlength='200' /></div></div>");})
		$('#check').click(function(){
			$("#choices").replaceWith("<div id='choices'><input type='hidden' name='qntype' value='CB'/><strong>Response Type: </strong>CheckBox <div class='fieldWrapper'><input type='checkbox' disabled='disabled'> <input id='id_choice1' type='text' name='choice1' maxlength='200' /></div><div class='fieldWrapper'><input type='checkbox' disabled='disabled'> <input id='id_choice2' type='text' name='choice2' maxlength='200' /></div><div class='fieldWrapper'><input type='checkbox' disabled='disabled'> <input id='id_choice3' type='text' name='choice3' maxlength='200' /></div><div class='fieldWrapper'><input type='checkbox' disabled='disabled'> <input id='id_choice4' type='text' name='choice4' maxlength='200' /></div></div>");})
		$('#number').click(function(){
			$("#choices").replaceWith("<div id='choices'><input type='hidden' name='qntype' value='NI'/><strong>Response Type: </strong>Numeric Input <br><input type='text' name='example' id='textboxfield2' readonly='readonly'/></div>");})
		console.log('Ready');
	});
</script>

{% endblock %}